apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ei2p2uykb-python 
  janus-idp.io/tekton: ei2p2uykb-python
  backstage.io/kubernetes-id: ei2p2uykb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ei2p2uykb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml