apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ei2p2uykb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ei2p2uykb-python 
  name: ei2p2uykb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ei2p2uykb-python 
